- name: Create VLANs and assign access ports
  hosts: ios
  gather_facts: no
  tasks:

    - name: Create VLANs
      ios_config:
        lines:
          - vlan {{ item.id }}
          - name {{ item.name }}
      loop: "{{ vlans }}"

    - name: Set access ports to VLANs
      ios_config:
        parents: "interface {{ item.interface }}"
        lines:
          - switchport mode access
          - switchport access vlan {{ item.vlan }}
      loop: "{{ access_ports }}"
