- name: Configure DHCP on IOS device
  hosts: ios
  gather_facts: no
  tasks:

    - name: Ensure DHCP service enabled
      ios_config:
        lines:
          - service dhcp

    - name: Create DHCP scopes
      ios_config:
        parents: "ip dhcp pool {{ item.name }}"
        lines:
          - network {{ item.network }}
          - default-router {{ item.default_router }}
          - dns-server {{ item.dns }}
      loop: "{{ dhcp_pools }}"
