- name: Configure Primary DNS Zone with Zone Transfer + Notification
  hosts: windows_dns
  gather_facts: no

  tasks:

    - name: Ensure DNS role installed
      ansible.windows.win_feature:
        name: DNS
        state: present

    - name: Create Primary DNS zone (AD-integrated)
      ansible.windows.win_dns_zone:
        name: "{{ dns_zone_name }}"
        zone_type: "{{ dns_zone_type }}"
        dynamic_update: Secure
        replication_scope: domain
        state: present

    - name: Allow zone transfers to secondaries
      ansible.windows.win_command:
        cmd: >
          dnscmd {{ ansible_hostname }}
          /zoneresetsecondaries {{ dns_zone_name }}
          /nonsecure2
          /secondary {{ secondary_dns_servers | join(' ') }}
      when: secondary_dns_servers is defined

    - name: Enable notify for secondaries
      ansible.windows.win_command:
        cmd: >
          dnscmd {{ ansible_hostname }}
          /zoneresetnotify {{ dns_zone_name }}
          {{ '1' if notify_secondaries else '0' }}
          {{ secondary_dns_servers | join(' ') }}
      when: notify_secondaries
