- name: Create Primary DNS Zone on Windows Server 2022
  hosts: windows_dns
  gather_facts: no

  tasks:
    - name: Ensure DNS role installed (optional safety)
      ansible.windows.win_feature:
        name: DNS
        state: present
      register: dns_role

    - name: Create the Primary DNS Zone
      ansible.windows.win_dns_zone:
        name: "{{ dns_zone_name }}"
        zone_type: "{{ dns_zone_type }}"
        dynamic_update: Secure
        replication_scope: domain
        state: present

    - name: Configure SOA record
      ansible.windows.win_dns_record:
        zone: "{{ dns_zone_name }}"
        name: "@"
        type: "SOA"
        primary_ns: "WIN-DC01.{{ dns_zone_name }}."
        admin_email: "{{ dns_admin_email }}"
        state: present
        
    - name: Add A record for web server
      ansible.windows.win_dns_record:
        zone: "{{ dns_zone_name }}"
        name: "www"
        type: "A"
        value: "192.168.100.50"
        state: present

    - name: Create Reverse Lookup Zone
      hosts: windows_dns
      gather_facts: no

      tasks:
        - name: Create reverse zone (192.168.100.0/24)
          ansible.windows.win_dns_zone:
            name: "100.168.192.in-addr.arpa"
            zone_type: "Primary"
            replication_scope: domain
            dynamic_update: Secure
            state: present
