- name: Create Secondary DNS Zone on Windows Server 2022
  hosts: windows_dns_secondary
  gather_facts: no

  tasks:
    - name: Ensure DNS role installed (optional safety)
      ansible.windows.win_feature:
        name: DNS
        state: present

    - name: Create Secondary DNS zone
      ansible.windows.win_dns_zone:
        name: "{{ dns_zone_name }}"
        zone_type: "{{ zone_type }}"
        master_servers:
          - "{{ primary_dns_ip }}"
        state: present
