dns_servers:
  - 1.1.1.1
  - 8.8.8.8

interfaces:
  - name: GigabitEthernet0/0
    ip: 10.10.10.1
    mask: 255.255.255.0
  - name: GigabitEthernet0/1
    ip: 172.16.0.1
    mask: 255.255.0.0

vlans:
  - id: 10
    name: USERS
  - id: 20
    name: SERVERS

access_ports:
  - interface: GigabitEthernet0/2
    vlan: 10
  - interface: GigabitEthernet0/3
    vlan: 20

ospf_process: 1
ospf_networks:
  - network: 10.10.10.0
    wildcard: 0.0.0.255
    area: 0
  - network: 172.16.0.0
    wildcard: 0.0.255.255
    area: 0
router_id: "{{ ansible_host }}"

static_routes:
  - dest: 192.168.100.0 255.255.255.0
    next_hop: 10.10.10.2
  - dest: 172.31.0.0 255.255.0.0
    next_hop: 172.16.0.2

dhcp_pools:
  - name: USERS_POOL
    network: 10.10.10.0 255.255.255.0
    default_router: 10.10.10.1
    dns: 1.1.1.1
  - name: SERVERS_POOL
    network: 172.16.0.0 255.255.255.0
    default_router: 172.16.0.1
    dns: 8.8.8.8

ftp_server: "192.168.50.10"
ftp_user: "ciscoftp"
ftp_pass: "SuperSecret123"
ftp_path: "backups"

# Standard ACL example
standard_acls:
  - number: 10
    remarks:
      - "Allow LAN"
    rules:
      - "permit 192.168.1.0 0.0.0.255"
      - "deny any"

# Extended ACL example
extended_acls:
  - name: BLOCK_BAD
    remarks:
      - "Block access to Server VLAN"
    rules:
      - "deny ip any 172.16.50.0 0.0.0.255"
      - "permit ip any any"

# ACL Interface Application
acl_interfaces:
  - interface: GigabitEthernet0/0
    inbound: "BLOCK_BAD"
  - interface: GigabitEthernet0/1
    outbound: "10"
