dns_zone_name: "example.local"
dns_zone_type: "Primary"

# Allowed zone transfer targets (secondary DNS servers)
secondary_dns_servers:
  - 192.168.100.11
  - 192.168.100.12

# Notify settings
notify_secondaries: true
